name: RUN TEST

on:
  pull_request:
    branches: [i3months]
  push:
    branches: [i3months]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: npm i
        run: npm ci

      - name: run test
        run: npm run test -- --run
